### PR TITLE
answers ?s to sprint challenge

### PR DESCRIPTION
**Pull request by fncischen**
@ryanboris

### CODE REVIEW

**Comment by fncischen** [comment]
almost complete with outline stage.

**Comment by fncischen** [comment]
all minimum code is rendered, now to check why the smurfs are not calling proper data api calls

**Comment by fncischen** [comment]
whoops forgot to dispatch action for the middleware, will do so now!

**Comment by fncischen** [comment]
I'm having issues calling this.props.gettingSmurfs, and my console log is returning this:

 Line 34:  Expected an assignment or function call and instead saw an expression  no-unused-expressions

**Comment by fncischen** [comment]
yay, turns out changing the localhost URL + adding the dispatch() to allow for thunk to operate made it work and render! thank you

**Review by secantsquared — APPROVED** [review]
💯

**Pull request merged**
